version: "3.8"

services:
  respondeai_backend:
    build: .
    container_name: respondeai_backend
    ports:
      - "3338:3000"
    networks:
      - proxy
    restart: always

networks:
  proxy:
    external: true
    name: traefik_proxy
 
